import '../styles/globals.css'
import { Inter } from 'next/font/google'
import NavBar from './components/Navbar'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
        <body className={inter.className}>
            <NavBar/>
            {children}
        </body>
    </html>
  )
}