import '../../../styles/globals.css'
import { Inter } from 'next/font/google'
import DropDownMenu from '../components/DropDownMenu'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Revistaria',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode}){



  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="fixed top-0 w-full grid grid-cols-2 h-12 items-center px-[10%] bg-[#4C5A77] text-yellow-500">
          <div>
            <Link href='/home' className="">Logo</Link>
          </div>
            <div className='flex justify-end'>
              <DropDownMenu/>
            </div>
        </div>
        <div className="px-4 pt-24">
            {children}
        </div>
      </body>
    </html>
  )
}
