'use client'

import '../../../styles/globals.css'
import { Inter } from 'next/font/google'
import DropDownMenu from '../components/DropDownMenu'
import Link from 'next/link'
import { usePathname } from 'next/navigation'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Revistaria',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode}){

  const pathname = usePathname()



  function handlePathname () {
    const trimedPathname = pathname.split('/').slice(1).map(e => e )

    return trimedPathname.map((element, index) =>         
      <Link href={`/${trimedPathname.slice(0, index + 1).join('/')}`} key={index} className='me-1'>

          <div className={`first-letter:uppercase inline-block`}>
            {element} /
          </div>
      </Link>)
  }


  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="fixed top-0 w-full grid grid-cols-2 h-12 items-center px-[10%] bg-[#4C5A77] text-[yellow]">
          <div>
            <Link href='/home' className="">Logo</Link>
          </div>
            <div className='flex justify-end'>
              <DropDownMenu/>
            </div>
        </div>
        <div className="">
            <div className='ms-[8%] px-4 pt-28 text-sm'>{handlePathname()}</div>
            {children}
        </div>
      </body>
    </html>
  )
}
