'use client'

import '../../../styles/globals.css'
import { Inter } from 'next/font/google'
import DropDownMenu from '../components/DropDownMenu'
import Link from 'next/link'
import { usePathname } from 'next/navigation'
import { searchIcon } from '../../../../public/icons/Icons'

const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Revistaria',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }: { children: React.ReactNode}){

  const pathname = usePathname()


  // function handlePathname () {
  //   const trimedPathname = pathname.split('/').slice(1).map(e => e )

  //   return trimedPathname.map((element, index) =>         
  //     <Link href={`/${trimedPathname.slice(0, index + 1).join('/')}`} key={index} className='me-1'>
  //         <div className={`first-letter:uppercase inline-block`}>
  //           {element} /
  //         </div>
  //     </Link>)
  // }

  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <header className="fixed top-0 w-full grid grid-cols-3 h-12 items-center px-[10%] bg-[#4C5A77] text-yellow-400">
          <div>
            <Link href='/home' className="">Logo</Link>
          </div>
          <div className='flex'>
            <input type="search"  className='w-full h-8 rounded-s-md px-3 outline-none' placeholder='Pesquisar'/>
            <button type='button' className='h-8 w-10 bg-yellow-400 rounded-e-md flex justify-center items-center'>{searchIcon}</button>
          </div>
          <div className='flex justify-end'>
            <DropDownMenu/>
          </div>
        </header> */}
        <div className="">
            <div className='ms-[8%] px-4 pt-28 text-sm'></div>
            {children}
        </div>
      </body>
    </html>
  )
}
